# Generated by Django 3.0.4 on 2020-12-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201213_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image_url_menu',
            field=models.TextField(default=' '),
        ),
    ]
