# Generated by Django 3.0.4 on 2020-12-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201213_0513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.AlterField(
            model_name='menu',
            name='image_url_menu',
            field=models.CharField(max_length=255),
        ),
    ]
