# Generated by Django 3.0.4 on 2020-12-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201213_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('imageUrl', models.TextField(default=' ')),
                ('description', models.TextField(default=' ')),
                ('menu', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
