# Generated by Django 3.0.4 on 2020-12-13 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dishcreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='api.Menu'),
        ),
    ]
